#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Rates.Resource", IsApplication=true)]

namespace Rates
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AUD1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BAT1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BGN1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BRL1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CAD1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CHF1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int closeico = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CLP1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int CNY1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CZK1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DKK1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int EUR1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int GBP1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int HKD1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int HRK1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int HUF1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IDR1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ILS1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int INR1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ISK1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int JPY1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int KRW1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int MXN1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int MYR1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int NOK1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int NZD1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int PHP1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int PLN1 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int RON1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int RUB1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int SEK1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int SGD1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int THB1 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int TRY1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int UAH1 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int USD1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int XDR1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ZAR1 = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int flag_country1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int flag_country2 = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int imgFlaga = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout3 = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int myListView = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int swich = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textView3 = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int txtAmount = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int txtBuy = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int txtDate = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int txtKod = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int txtMid = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int txtName = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int txtRate = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int txtResult = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int txtSell = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_k = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListView_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
